INSERT INTO category(category_id, category_name) VALUES('000', '全て');
INSERT INTO category(category_id, category_name) VALUES('001', '肉類');
INSERT INTO category(category_id, category_name) VALUES('002', '魚介類');
INSERT INTO category(category_id, category_name) VALUES('003', '野菜類');
INSERT INTO category(category_id, category_name) VALUES('004', '乳製品・卵');
INSERT INTO category(category_id, category_name) VALUES('005', '加工品');
INSERT INTO category(category_id, category_name) VALUES('006', '豆類');
INSERT INTO category(category_id, category_name) VALUES('007', '飲料');
INSERT INTO category(category_id, category_name) VALUES('008', 'その他');
